# Permalinks
permalink:           pretty

# Setup
title:               Lexie Holthaus
# tagline:             Software Developer from Chicago.
url:                 https://lexieholthaus.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            compressed

# About/contact
author:
  name:              Lexie Holthaus
  # url:               https://hachyderm.io/@jamigibbs
  # email:             jami0821@gmail.com

# Custom vars
version:             2.0.1
github:
  repo:              https://github.com/LexieHolthaus
  # repo:              https://github.com/jamigibbs/portfolio
# google_analytics:    UA-3363703-15
# twitter:             jamigibbs
github:              lexieholthaus
# dribbble:            jamigibbs

# Gems
plugins:
  # - jekyll-paginate
  # - jekyll-gist
